//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBlast_2._0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockBlast_2._0.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 секунд.
        /// </summary>
        internal static string _10s {
            get {
                return ResourceManager.GetString("10s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 секунд.
        /// </summary>
        internal static string _15s {
            get {
                return ResourceManager.GetString("15s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 секунд.
        /// </summary>
        internal static string _30s {
            get {
                return ResourceManager.GetString("30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 секунд.
        /// </summary>
        internal static string _5s {
            get {
                return ResourceManager.GetString("5s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Clear_Date {
            get {
                return ResourceManager.GetString("Clear-Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок.
        /// </summary>
        internal static string Clear_Player {
            get {
                return ResourceManager.GetString("Clear-Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очки.
        /// </summary>
        internal static string Clear_Score {
            get {
                return ResourceManager.GetString("Clear-Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сейчас ходит: Игрок {0}.
        /// </summary>
        internal static string Current_Player {
            get {
                return ResourceManager.GetString("Current-Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра на 2х игроков.
        /// </summary>
        internal static string Duo {
            get {
                return ResourceManager.GetString("Duo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четыре игрока.
        /// </summary>
        internal static string Four_Players {
            get {
                return ResourceManager.GetString("Four-Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockBlast 2.0 - {0} игрока(ов).
        /// </summary>
        internal static string Game_SubTitle {
            get {
                return ResourceManager.GetString("Game-SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец игры.
        /// </summary>
        internal static string GameEnd {
            get {
                return ResourceManager.GetString("GameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица лидеров.
        /// </summary>
        internal static string Leaderboard {
            get {
                return ResourceManager.GetString("Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} сек..
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockBlast - Меню.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время на ход истекло! Ход переходит к следующему игроку..
        /// </summary>
        internal static string Move_Time_Expired {
            get {
                return ResourceManager.GetString("Move-Time-Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок не может сделать ход. Ход переходит к следующему игроку..
        /// </summary>
        internal static string Move_Unavailable {
            get {
                return ResourceManager.GetString("Move-Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыка: Выкл.
        /// </summary>
        internal static string Music_Off {
            get {
                return ResourceManager.GetString("Music-Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыка: Вкл.
        /// </summary>
        internal static string Music_On {
            get {
                return ResourceManager.GetString("Music-On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при воспроизведении музыки: {0}.
        /// </summary>
        internal static string Music_Player_Error {
            get {
                return ResourceManager.GetString("Music-Player-Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пока нет записей.
        /// </summary>
        internal static string No_Entries {
            get {
                return ResourceManager.GetString("No-Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет лимита.
        /// </summary>
        internal static string No_Limit {
            get {
                return ResourceManager.GetString("No-Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без ограничения.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одни игрок.
        /// </summary>
        internal static string One_Player {
            get {
                return ResourceManager.GetString("One-Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок {0}.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра на 4х игроков.
        /// </summary>
        internal static string Quadro {
            get {
                return ResourceManager.GetString("Quadro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очки: {0}.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одиночная игра.
        /// </summary>
        internal static string Solo {
            get {
                return ResourceManager.GetString("Solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при воспроизведении звука: {0}.
        /// </summary>
        internal static string Sound_Player_Error {
            get {
                return ResourceManager.GetString("Sound-Player_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки: Выкл.
        /// </summary>
        internal static string Sounds_Off {
            get {
                return ResourceManager.GetString("Sounds-Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки: Вкл.
        /// </summary>
        internal static string Sounds_On {
            get {
                return ResourceManager.GetString("Sounds-On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Времени осталось: {0} сек..
        /// </summary>
        internal static string Time_Left {
            get {
                return ResourceManager.GetString("Time-Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимит времени на ход:.
        /// </summary>
        internal static string Time_Limit_Per_Turn {
            get {
                return ResourceManager.GetString("Time-Limit-Per-Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockBlast 2.0.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ 10 результатов:.
        /// </summary>
        internal static string Top_10_Results {
            get {
                return ResourceManager.GetString("Top-10-Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два игрока.
        /// </summary>
        internal static string Two_Players {
            get {
                return ResourceManager.GetString("Two-Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время на ход не ограничено.
        /// </summary>
        internal static string Unlimited_Time {
            get {
                return ResourceManager.GetString("Unlimited-Time", resourceCulture);
            }
        }
    }
}
